networks:
  my-app-network:
    external: true
services:
  frontend-table:
    build: .
    container_name: frontend_table
    expose:
      - "80"
    networks:
      - my-app-network
    environment:
      - VITE_API_URL=http://localhost:1414/api
